version: '3.8'
services:
  api:
    build: ./api
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
  worker:
    build: ./bg_tasks
    depends_on:
      - api
      - redis